services:
  matrix-push-gateway:
    build: .
    container_name: matrix-push-gateway
    restart: unless-stopped
    env_file: .env
    networks:
      - matrix-internal

networks:
  matrix-internal:
    name: matrix-internal
